### PR TITLE
fixes #20 custom hostname not used

### LINKED ISSUE #20: custom hostname not used
```
- hosts: 10.0.0.5
  roles:
    - { role: fqdn, fqdn: "mx.mydomain.com", hostname: "mx" }
```

/etc/hosts has the content:

`10.0.0.5 mx.mydomain.com 10`

but should have

`10.0.0.5 mx.mydomain.com mx`

### PR DESCRIPTION
**Pull request by davidak**
tested on Ubuntu 16.04

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
:+1: ping @holms

**Comment by holms** [comment]
Hi :) what's this pus is all about? I'm using custom hostnames, usually it's a group name of inventory and just a numbering for each node.

**Comment by ernestas-poskus** [comment]
> https://github.com/holms/ansible-fqdn/blob/master/defaults/main.yml#L3

```yaml
---
fqdn: "{{ inventory_hostname }}"
hostname: "{{ inventory_hostname_short }}"
```

there is no way to control ```inventory_hostname_short``` without this fix

**Comment by holms** [comment]
Well you put a variable to inventory file near your ip address.. Ive stated this in readme file (unless its gone by previou pull requests)

-----Original Message-----

**Comment by davidak** [comment]
@holms i've also created a bugreport that explains the problem: https://github.com/holms/ansible-fqdn/issues/20

**Pull request merged**
